version: '3.2'
services:
  xnodejs:
    hostname: xnodejs
    container_name: xnodejs
    build:
      context: .
      dockerfile: docker/nodejs.dockerfile
    volumes:
      - ./:/var/app
    networks:
      - default
  xapache:
    hostname: xapache
    container_name: xapache
    build:
      context: .
      dockerfile: docker/apache.dockerfile
    ports:
      - '7777:443'
    volumes:
      - ./docker/apache/extra:/usr/local/apache2/conf/extra
    networks:
      - default
