version: '3.2'
services:
  xnodejs:
    hostname: xnodejs
    container_name: xnodejs
    build:
      context: .
      dockerfile: docker/nodejs.dockerfile
    volumes:
      - ./:/var/app
    networks:
      - default
  xapache:
    hostname: xapache
    container_name: xapache
    build:
      context: .
      dockerfile: docker/apache.dockerfile
    ports:
      - '7777:80'
    volumes:
      - ./docker/apache/extra:/usr/local/apache2/conf/extra
    networks:
      - default
  xnginx:
    image: nginx:1.15
    hostname: xnginx
    container_name: xnginx
    working_dir: /var/www/html
    ports:
      - "8888:80"
    volumes:
      - ./apps/nuxt-app:/var/www/html/nuxt-app
      - ./docker/nginx/ssl:/etc/ssl:ro
      - ./docker/nginx/auth:/etc/nginx/auth
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-dev:/etc/nginx/sites-enabled
    networks:
      - default

